### PR TITLE
update jdk location

### PR DESCRIPTION
**Pull request by devkimittal**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

### CODE REVIEW

**Comment by devkimittal** [comment]
trigger compile

**Comment by devkimittal** [comment]
trigger

**Comment by devkimittal** [comment]
made_a_comment

**Comment by devkimittal** [comment]
edited

**Comment by devkimittal** [comment]
another_comment

**Comment by harshjain12** [comment]
hjhjdfhjhfdhhjfdhjfdhjfdhj

**Comment by devkimittal** [comment]
new_comment

**Comment by devkimittal** [comment]
trigger buildnum

**Comment by vistaarjuneja** [comment]
test

**Comment by devkimittal** [comment]
bybyybu

**Comment by devkimittal** [comment]
hiii

**Comment by devkimittal** [comment]
cgvhg

**Comment by devkimittal** [comment]
condjfrfr

**Comment by devkimittal** [comment]
cd_trigger

**Comment by devkimittal** [comment]
dbhabdenkcrv

**Comment by devkimittal** [comment]
pr_comment1

**Comment by devkimittal** [comment]
🔢

**Comment by devkimittal** [comment]
hello

**Pull request closed without merging**
